Circulatory system
Terasology/Anatomy pull request #6
Opened 2017-06-19 16:29 UTC by arpan98

A circulatory system similar to the Skeletal system with part "healths".
An additional feature of overall blood level, based on which different effects can be caused.

2017-06-21 04:45 UTC, Cervator requested changes
Looks good overall and tests out :-)

I noted a few issues:

* `showCirculatoryHealths` doesn't seem to show a number for blood level if you run it as the first thing (after taking damage once it then populated). Something not initialized?
* I could manage to die from blood loss, but the death screen doesn't indicate that it is blood loss, just physical damage - maybe add a new damage type of blood loss induced damage/death?
* *After* dying from blood loss if I respawned right away I would immediately die from blood loss again - this might relate to some of @nihal111's work on preserving the player's entity after death for some other reasons, probably an easy fix. If you don't have latest engine pull it and give it a try, maybe ask him on Slack. If you just wait a while (the blood pool is regenerating even while dead) you can then respawn fine
* It might be something trying to clarify the different types of regen, as it is very easy to confuse regular HP regen and blood pool regen

2017-06-21 04:45 UTC, Cervator commented on src/main/java/org/terasology/anatomy/AnatomyCirculation/CirculatorySystem.java
> +        return "Healths fully restored.";
This could probably be more descriptive (indicating this is circulation related not general health)

2017-06-21 07:29 UTC, arpan98 commented
- So this happens because the details are stored in the `InjuredCirculatoryComponent` which is attached on to the player when he is first damaged. A solution could be showing the default value (this might change further if we introduce genetics or so) or showing something like "Full" if the component does not exist.

- I was meaning to ask about this. Does blood loss as a damage type make sense? Which parent type does it draw from? Also, since blood loss is not a direct result of someone else doing damage on you, the instigator should be the player himself, right?

2017-06-22 16:08 UTC, mjuvekar7 commented on src/main/java/org/terasology/anatomy/AnatomyCirculation/CirculatoryEffectsSystem.java
> +        if (injuredCirculatoryComponent.bloodLevel == 0) {
Change this to `if (injuredCirculatoryComponent.bloodLevel <= 0)` and remove the if block here https://github.com/Terasology/Anatomy/pull/6/files#diff-c2e4e0e861707aa511ad08dff8a9529bR134 (good practice; will prevent small potential problems that could be overlooked if/when more people contribute to the module)

2017-06-22 16:19 UTC, arpan98 commented on src/main/java/org/terasology/anatomy/AnatomyCirculation/CirculatoryEffectsSystem.java
> +        if (injuredCirculatoryComponent.bloodLevel == 0) {
Good point. I'll make the change here. But I don't think I'll remove the if block there (I should change it to `TeraMath.clamp()`), don't want the level to go below 0.

2017-06-22 16:56 UTC, Cervator commented
* Initial logging: I think that yeah if the injured component simply doesn't exist you can safely assume "Healthy" or what not
* Blood loss does IMHO make sense as a damage type, although perhaps more accurately as a _death type_ - but effectively the final damage type becomes the death type. So that's fine. Yeah instigator is the player even if indirectly the damage causing the initial wound would be to blame. So "You died from blood loss" is fine, "You died from blood loss, caused by injury X originating from Y" would be even better but trickier - maybe later.
* Great :-)
* Regen when referred to in logging/console would be nice to have more detailed. So "Blood regen" or "HP regen" for instance, instead of two separate "Regen" - most important for player display, but naturally nice to have clear in code as well.

2017-07-01 16:56 UTC, merged